[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mosairt"
version = "0.1.0-alpha"
description = "Bibliothèque IRT (1PL à 4PL) pour le projet Mosaik / OULAD"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "scikit-learn"
]

[tool.setuptools]
package-dir={"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["irt*"]

[project.scripts]
run-mosairt = "main:run_experiment_entry"